#!/bin/bash

# This script produces the file data_out.txt
# It presents the data rate impact [bps] as a function of the sampling ratio.
# The user traffic rate (not including IOAM overhead) is 1 mbps (generated by 833000 bps in Iperf)

# Before running this script make sure that (1) run_iperf.sh is running in a separate shell window. (2) run_tshark.sh is running in a separate shell window. For further details see README.md.

# Note that the sampling ratio is directly correlated to the IOAM overhead - each IOAM-enabled packet has an 80 byte overhead (8 bytes of IOAM data per hop + 8 bytes of IOAM header + 4 bytes IPv6 extension header + 44 bytes IPv6 tunnel).

# ratio is the sampling ratio. For example, a sampling ratio of 128 means that 1 out of every 128 packets is encapsulated with IOAM.

ratio=(128 64 32 16 10 8 6 4 2 1)
iterations=10
TestTime=20

sudo lxc-attach -n alpha -- bash -c "iperf3 -6 -b 10000 -c db03::2 -u -l 298 -t2"

echo "SamplingRatio DataImpact[bps]" > data_out.txt
# A samping ratio '0' indicates no IOAM:
echo 0 0 >> data_out.txt

exec 2> /dev/null
prev=$(cat tmp_tshark.txt | grep "db00::2" | grep "UDP" | grep -v "62,63" | awk '{print $1}' | awk '{ sum += $1 } END { print sum }')
sudo lxc-attach -n athos -- bash -c "./athos/ioam_unregister"
sudo lxc-attach -n alpha -- bash -c "iperf3 -6 -b 833000 -c db03::2 -u -l 298 -t20"
sleep 1
current=$(cat tmp_tshark.txt | grep "db00::2" | grep "UDP" | grep -v "62,63" | awk '{print $1}' | awk '{ sum += $1 } END { print sum }')
unobserved=$(($current-$prev))
prev=$current
sudo lxc-attach -n athos -- bash -c "./athos/ioam_register 1"

for ((i=0; i<iterations; i++))
do
    sudo lxc-attach -n athos -- bash -c "./athos/ioam_unregister"
    sudo lxc-attach -n athos -- bash -c "./athos/ioam_register ${ratio[i]}"
    sudo lxc-attach -n alpha -- bash -c "iperf3 -6 -b 833000 -c db03::2 -u -l 298 -t20"
    sleep 5
    
    current=$(cat tmp_tshark.txt | grep "db00::2" | grep "UDP" | grep -v "62,63" | awk '{print $1}' | awk '{ sum += $1 } END { print sum }')
    Result=$(($current-$prev-$unobserved))
    Result=$(($Result*8/$TestTime))
    prev=$current
    echo ${ratio[i]} $Result >> data_out.txt
done

